spring:
  application:
    name: verx-task-api
  liquibase:
    change-log: classpath:db/changelog/master.xml

cors:
  allowed-origins: http://localhost:8080

logging:
  level:
    root: INFO
    br.com.higorcraco: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
